server:
  port: 8080
spring:
  scheduler:
    poolSize: 5
  datasource:
    url: jdbc:mysql://101.132.153.126/psm_v2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
    open-in-view: true
  jackson:
    time-zone: GMT+8
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      cache: false
      mode: LEGACYHTML5

#log4j:
#  logger:
#    org:
#      thymeleaf: DEBUG
#        TemplateEngine:
#          CONFIG: TRACE
#          TIMER: TRACE
#          TEMPLATE_CACHE: TRACE
